#!/usr/bin/env python3
"""Build the curated beauty enrichment layer."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
RAW_ROOT = ROOT / "data" / "raw" / "ecommerce_agent_dataset"
OUTPUT = ROOT / "data" / "enriched" / "beauty_products.jsonl"


def make_annotation(
    *,
    target_users: list[str],
    use_cases: list[str],
    selling_points: list[str],
    cautions: list[str],
    avoid_for: list[str],
    suitable_for: list[str],
    tags: list[str],
    skin_types: list[str],
    skin_concerns: list[str],
    product_effects: list[str],
    key_ingredients: list[str],
    texture: str,
    card_reason: str,
    spf: str = "",
    pa: str = "",
    makeup_compatibility: str = "",
    sensitive_skin_note: str = "敏感肌首次使用建议先做耳后或局部测试。",
    avoid_conditions: list[str] | None = None,
) -> dict[str, Any]:
    return {
        "attributes": {
            "target_users": target_users,
            "use_cases": use_cases,
            "selling_points": selling_points,
            "cautions": cautions,
            "avoid_for": avoid_for,
            "suitable_for": suitable_for,
            "tags": tags,
        },
        "beauty_attributes": {
            "skin_types": skin_types,
            "skin_concerns": skin_concerns,
            "product_effects": product_effects,
            "key_ingredients": key_ingredients,
            "texture": texture,
            "spf": spf,
            "pa": pa,
            "makeup_compatibility": makeup_compatibility,
            "sensitive_skin_note": sensitive_skin_note,
            "avoid_conditions": avoid_conditions or [],
        },
        "card_reason": card_reason,
    }


ANNOTATIONS: dict[str, dict[str, Any]] = {
    "p_beauty_001": make_annotation(
        target_users=["25+初抗老人群", "熬夜暗沉人群", "有干纹细纹的人"],
        use_cases=["夜间修护", "熬夜后修护", "抗初老护理"],
        selling_points=["二裂酵母发酵产物溶胞物", "透明质酸保湿", "淡纹紧致", "夜间修护"],
        cautions=["价格较高", "开封后6个月内用完", "敏感肌先做耳后测试"],
        avoid_for=["预算有限的人", "急性敏感期人群", "混油皮担心闭口的人"],
        suitable_for=["干纹细纹", "熬夜暗沉", "初抗老需求"],
        tags=["精华", "抗初老", "修护", "保湿", "淡纹"],
        skin_types=["多数肤质"],
        skin_concerns=["干纹", "细纹", "暗沉", "屏障受损"],
        product_effects=["抗初老", "修护", "保湿", "淡纹"],
        key_ingredients=["二裂酵母发酵产物溶胞物", "透明质酸", "猴面包树籽提取物"],
        texture="精华露",
        makeup_compatibility="夜间护肤精华，不是底妆产品；白天使用需做好防晒。",
        sensitive_skin_note="含活性修护成分，敏感肌需先做耳后测试。",
        avoid_conditions=["急性泛红刺痛期", "对发酵类成分不耐受"],
        card_reason="适合预算充足、想做夜间修护和抗初老的人，主打保湿修护与淡纹紧致。",
    ),
    "p_beauty_002": make_annotation(
        target_users=["25+初抗老人群", "换季不稳定肌肤", "熬夜暗沉人群", "毛孔粗大人群"],
        use_cases=["肌底打底", "换季维稳", "熬夜急救", "后续精华前打底"],
        selling_points=["高纯度二裂酵母", "益生元复合物", "修护维稳", "细腻毛孔"],
        cautions=["价格较高", "开封后6个月内用完", "敏感肌少量建立耐受"],
        avoid_for=["预算有限的人", "对发酵类成分不耐受的人"],
        suitable_for=["皮肤不稳定", "熬夜暗沉", "初抗老", "毛孔粗大"],
        tags=["精华", "维稳", "修护", "提亮", "毛孔"],
        skin_types=["多数肤质", "混油皮"],
        skin_concerns=["不稳定", "毛孔", "暗沉", "初老"],
        product_effects=["修护", "维稳", "提亮", "细腻毛孔"],
        key_ingredients=["二裂酵母发酵产物溶胞物", "益生元复合物"],
        texture="清爽精华肌底液",
        makeup_compatibility="护肤第一步使用，后续可叠加功效精华或面霜。",
        sensitive_skin_note="敏感肌建议从少量、低频开始，观察24小时后再全脸使用。",
        avoid_conditions=["急性敏感期", "与酸类高频叠加"],
        card_reason="更偏肌底维稳和后续吸收打底，适合换季不稳定或熬夜暗沉但预算充足的人。",
    ),
    "p_beauty_003": make_annotation(
        target_users=["25+初老肌", "毛孔粗大人群", "角质粗糙人群", "暗沉人群"],
        use_cases=["洁面后第一步", "T区擦拭", "熬夜湿敷急救", "角质调理"],
        selling_points=["PITERA酵母发酵滤液", "调理角质", "收缩毛孔", "水晶透亮"],
        cautions=["价格高", "发酵味明显", "敏感肌需逐步建立耐受"],
        avoid_for=["干皮觉得保湿不足的人", "敏感肌无法耐受发酵调理的人", "预算有限的人"],
        suitable_for=["毛孔粗大", "角质粗糙", "肤色暗沉", "油皮混油皮"],
        tags=["化妆水", "毛孔", "提亮", "角质", "高预算"],
        skin_types=["油皮", "混油皮", "多数肤质"],
        skin_concerns=["毛孔", "角质粗糙", "暗沉", "闭口"],
        product_effects=["提亮", "调理角质", "收缩毛孔", "保湿"],
        key_ingredients=["PITERA酵母发酵滤液"],
        texture="清透护肤精华露",
        makeup_compatibility="护肤第一步，可在妆前少量轻拍；干皮需叠加保湿。",
        sensitive_skin_note="敏感肌初期每周2-3次少量使用，若持续红肿刺痛应停用。",
        avoid_conditions=["屏障受损期频繁湿敷", "对发酵酸味或调理角质不耐受"],
        card_reason="适合高预算、想改善毛孔粗糙和暗沉的人；敏感肌和干皮要谨慎建立耐受。",
    ),
    "p_beauty_004": make_annotation(
        target_users=["换季敏感人群", "熬夜暗沉人群", "长期外界刺激人群", "干敏皮"],
        use_cases=["换季维稳", "熬夜后修护", "肌底精华", "早晚护肤"],
        selling_points=["ULTIMUNE肌活复合物", "强韧肌底", "舒缓保湿", "维稳修护"],
        cautions=["敏感肌先测试", "开封后按规格尽快用完", "避免和高刺激产品高频叠加"],
        avoid_for=["讨厌轻微黏感的人", "急性过敏期人群"],
        suitable_for=["换季泛红", "肌肤不稳定", "熬夜暗沉", "屏障脆弱"],
        tags=["精华", "维稳", "修护", "舒缓", "保湿"],
        skin_types=["干皮", "敏感肌", "多数肤质"],
        skin_concerns=["泛红", "不稳定", "暗沉", "屏障脆弱"],
        product_effects=["修护", "维稳", "舒缓", "保湿"],
        key_ingredients=["ULTIMUNE肌活复合物", "保加利亚玫瑰水", "透明质酸"],
        texture="蛋清状精华",
        makeup_compatibility="肌底精华，后续可接其他功能精华或面霜。",
        sensitive_skin_note="主打维稳但仍需先做局部测试，急性敏感期先缓解症状。",
        avoid_conditions=["红肿刺痛未缓解", "高浓度酸类同时叠加"],
        card_reason="适合想做换季维稳和屏障强韧的人，尤其是熬夜后肌肤不稳定场景。",
    ),
    "p_beauty_005": make_annotation(
        target_users=["日晒斑人群", "痘印色沉人群", "熬夜暗沉人群", "长期面对电脑的人"],
        use_cases=["淡斑提亮", "早晚护肤", "日晒后色沉护理", "痘印护理"],
        selling_points=["乙基维生素C", "玻色因", "透明质酸", "温和淡斑"],
        cautions=["白天必须配合防晒", "淡斑需4-8周持续使用", "敏感肌先测试"],
        avoid_for=["期待立刻淡斑的人", "不愿意配合防晒的人", "急性敏感期人群"],
        suitable_for=["日晒斑", "痘印色沉", "肤色不均", "暗沉"],
        tags=["精华", "淡斑", "提亮", "保湿", "维C"],
        skin_types=["多数肤质"],
        skin_concerns=["色斑", "痘印", "暗沉", "肤色不均"],
        product_effects=["淡斑", "提亮", "保湿", "修护"],
        key_ingredients=["乙基维生素C", "玻色因", "透明质酸"],
        texture="清爽精华液",
        makeup_compatibility="护肤精华，白天使用后需叠加防晒。",
        sensitive_skin_note="含提亮类活性成分，敏感肌先测试，出现红肿刺痛应停用。",
        avoid_conditions=["白天不用防晒", "急性泛红刺痛"],
        card_reason="适合想淡化痘印、日晒斑和提亮肤色的人，但必须配合防晒才合理。",
    ),
    "p_beauty_006": make_annotation(
        target_users=["油皮", "混油皮", "通勤人群", "学生党"],
        use_cases=["日常通勤防晒", "短途户外", "妆前打底"],
        selling_points=["SPF50+ PA++++", "水感轻薄", "自然提亮", "200元以内"],
        cautions=["敏感肌先做耳后测试", "长时间户外需2-3小时补涂"],
        avoid_for=["长时间大量出汗场景", "对防晒剂敏感人群"],
        suitable_for=["油皮", "混油皮", "追求清爽肤感的人"],
        tags=["防晒", "油皮", "通勤", "轻薄", "200元以内"],
        skin_types=["油皮", "混油皮"],
        skin_concerns=["出油", "防晒", "暗沉"],
        product_effects=["防晒", "修护", "提亮"],
        key_ingredients=["玻尿酸", "维生素E"],
        texture="水感轻薄",
        spf="SPF50+",
        pa="PA++++",
        makeup_compatibility="可叠加粉底或散粉",
        sensitive_skin_note="敏感肌需先做耳后测试",
        avoid_conditions=["大量出汗后不补涂", "眼周或破损肌肤"],
        card_reason="SPF50+ PA++++，水感轻薄，适合油皮/混油皮通勤防晒，价格在200元以内。",
    ),
    "p_beauty_007": make_annotation(
        target_users=["敏感肌", "屏障受损人群", "干痒泛红人群"],
        use_cases=["屏障修护", "换季维稳", "保湿舒缓", "医美后基础修护"],
        selling_points=["舒敏保湿", "修护屏障", "舒缓干痒", "马齿苋提取物"],
        cautions=["严重敏感期建议先少量试用", "避免与刺激性产品叠加"],
        avoid_for=["只追求强功效抗老的人"],
        suitable_for=["敏感肌", "干敏肌", "屏障不稳定人群"],
        tags=["敏感肌", "修护", "保湿", "面霜", "屏障"],
        skin_types=["敏感肌", "干敏肌"],
        skin_concerns=["屏障受损", "干痒", "泛红", "缺水"],
        product_effects=["舒缓", "保湿", "修护屏障"],
        key_ingredients=["马齿苋提取物", "青刺果油", "透明质酸"],
        texture="特护面霜",
        makeup_compatibility="适合护肤保湿步骤，不是底妆产品。",
        sensitive_skin_note="敏感肌友好，但仍建议先局部测试。",
        avoid_conditions=["急性红肿刺痛未缓解时大面积使用", "与刺激性产品叠加"],
        card_reason="主打敏感肌舒缓保湿和屏障修护，适合屏障不稳定时作为温和选项。",
    ),
    "p_beauty_008": make_annotation(
        target_users=["25+初抗老人群", "干皮", "秋冬保湿需求", "想紧致淡纹的人"],
        use_cases=["日霜保湿", "秋冬滋润", "颈部提拉按摩", "出差随身护理"],
        selling_points=["烟酰胺", "五胜肽", "透明质酸", "紧致提拉"],
        cautions=["敏感肌先测试", "滋润型油皮可能觉得厚重", "开封后6个月内用完"],
        avoid_for=["大油皮厚涂", "烟酰胺不耐受人群", "讨厌面霜肤感的人"],
        suitable_for=["干皮", "初老细纹", "肤色暗沉", "保湿需求"],
        tags=["面霜", "抗初老", "保湿", "淡纹", "紧致"],
        skin_types=["干皮", "中性肌", "多数肤质"],
        skin_concerns=["细纹", "松弛", "干燥", "暗沉"],
        product_effects=["抗初老", "淡纹", "紧致", "保湿", "提亮"],
        key_ingredients=["烟酰胺", "五胜肽", "透明质酸"],
        texture="日霜/滋润型面霜",
        makeup_compatibility="日霜款可做妆前保湿；滋润型妆前需控制用量。",
        sensitive_skin_note="含烟酰胺和胜肽，敏感肌需先测试耐受。",
        avoid_conditions=["油皮白天厚涂", "烟酰胺不耐受"],
        card_reason="适合想用面霜做抗初老、淡纹和保湿的人，干皮或秋冬场景更匹配。",
    ),
    "p_beauty_009": make_annotation(
        target_users=["25+初抗老人群", "熬夜暗沉人群", "长期面对电子屏的人"],
        use_cases=["抗氧抗糖", "熬夜急救", "早晚精华", "提亮肤色"],
        selling_points=["麦角硫因", "虾青素", "抗氧抗糖", "50ml容量"],
        cautions=["敏感肌先测试", "开封后6个月内用完", "避免阳光直射存放"],
        avoid_for=["对抗氧化活性成分不耐受的人", "只需要基础保湿的人"],
        suitable_for=["暗沉蜡黄", "初老细纹", "熬夜肌", "屏幕党"],
        tags=["精华", "抗初老", "提亮", "抗氧", "熬夜"],
        skin_types=["多数肤质"],
        skin_concerns=["暗沉", "糖化", "初老", "细纹"],
        product_effects=["抗初老", "抗氧", "提亮", "保湿"],
        key_ingredients=["麦角硫因", "虾青素"],
        texture="精华液",
        makeup_compatibility="护肤精华，妆前需等待吸收后再上底妆。",
        sensitive_skin_note="敏感肌先做皮肤测试，初期可降低频率。",
        avoid_conditions=["急性敏感期", "对虾青素或活性抗氧成分不耐受"],
        card_reason="适合熬夜暗沉和初抗老人群，价格比大牌抗老精华更友好。",
    ),
    "p_beauty_010": make_annotation(
        target_users=["户外活动人群", "需要防水防汗的人", "面部身体防晒需求"],
        use_cases=["海边", "爬山", "长时间户外", "运动防晒"],
        selling_points=["SPF50+ PA++++", "遇水增强技术", "防水防汗", "户外适用"],
        cautions=["需要卸妆清洁", "敏感肌先测试", "户外仍需补涂"],
        avoid_for=["不喜欢成膜感的人", "只需要轻薄通勤的人"],
        suitable_for=["户外场景", "运动场景", "需要防水防汗的人"],
        tags=["防晒", "户外", "防水防汗", "高倍防晒", "运动"],
        skin_types=["多数肤质"],
        skin_concerns=["防晒", "晒黑", "晒伤"],
        product_effects=["防晒", "防水", "防汗"],
        key_ingredients=["Aqua Booster EX"],
        texture="快速成膜防晒乳",
        spf="SPF50+",
        pa="PA++++",
        makeup_compatibility="更偏户外防护，不主打妆前轻薄。",
        sensitive_skin_note="敏感肌需先做局部测试。",
        avoid_conditions=["讨厌成膜感", "清洁不到位"],
        card_reason="更适合长时间户外或运动防晒，防水防汗比轻薄通勤款更突出。",
    ),
    "p_beauty_011": make_annotation(
        target_users=["中性肌", "混合肌", "日常清洁人群", "预算有限的人"],
        use_cases=["晨间洁面", "晚间二次清洁", "淡妆后清洁", "日常基础清洁"],
        selling_points=["绵密泡沫", "蚕丝蛋白精华", "双重透明质酸", "价格低"],
        cautions=["干皮洗后需及时保湿", "敏感肌先测试", "避免入眼"],
        avoid_for=["极干皮追求无紧绷的人", "急性敏感期人群"],
        suitable_for=["中性肌", "混合肌", "日常清洁", "学生党"],
        tags=["洁面", "清洁", "保湿", "平价", "泡沫"],
        skin_types=["中性肌", "混合肌"],
        skin_concerns=["油脂污垢", "淡妆残留", "毛孔清洁"],
        product_effects=["清洁", "保湿"],
        key_ingredients=["蚕丝蛋白精华", "透明质酸"],
        texture="绵密泡沫洁面乳",
        makeup_compatibility="洁面产品，淡妆后可做二次清洁，不替代专业卸妆。",
        avoid_conditions=["眼周直接接触", "干皮洗后不保湿"],
        card_reason="适合预算有限、想做日常泡沫清洁的人；干皮和敏感肌要注意洗后保湿与测试。",
    ),
    "p_beauty_012": make_annotation(
        target_users=["敏感肌", "干皮", "需要滋润修护的人"],
        use_cases=["夜间修护", "换季保湿", "干皮滋润", "泛红急救厚敷"],
        selling_points=["理肤泉温泉水", "神经酰胺", "乳木果油", "滋润修护"],
        cautions=["油皮可能觉得厚重", "首次使用先局部测试", "出现刺痛红肿应停用"],
        avoid_for=["大油皮", "讨厌厚重肤感的人"],
        suitable_for=["干皮", "敏感肌", "屏障修护需求"],
        tags=["敏感肌", "干皮", "修护", "保湿", "面霜"],
        skin_types=["干皮", "敏感肌"],
        skin_concerns=["干燥", "屏障脆弱", "泛红", "紧绷"],
        product_effects=["保湿", "舒缓", "修护"],
        key_ingredients=["理肤泉温泉水", "神经酰胺3和4", "乳木果油", "甘油"],
        texture="滋润型面霜",
        makeup_compatibility="更适合护肤修护，妆前需控制用量。",
        sensitive_skin_note="敏感肌适用但仍需先测试。",
        avoid_conditions=["油皮白天厚涂", "出现刺痛红肿仍继续使用"],
        card_reason="滋润修护取向更强，适合干皮或敏感肌做屏障修护。",
    ),
    "p_beauty_013": make_annotation(
        target_users=["油皮", "混油皮", "夏季带妆人群", "随身补妆需求"],
        use_cases=["控油定妆", "T区补妆", "夏季通勤", "长时间带妆"],
        selling_points=["柔焦毛孔", "控油定妆", "粉质细腻", "百元以内"],
        cautions=["干皮需做好保湿打底", "取粉后抖掉余粉", "补充装不含外壳"],
        avoid_for=["干皮未做保湿打底", "不需要定妆的人"],
        suitable_for=["油皮", "混油皮", "毛孔明显", "预算有限"],
        tags=["蜜粉", "定妆", "控油", "毛孔", "百元以内"],
        skin_types=["油皮", "混油皮"],
        skin_concerns=["出油", "毛孔", "脱妆", "暗沉"],
        product_effects=["定妆", "控油", "柔焦", "提亮"],
        key_ingredients=["细腻粉体"],
        texture="蜜粉饼",
        makeup_compatibility="底妆后按压定妆，T区可重点补妆。",
        sensitive_skin_note="敏感肌或粉体敏感人群先做局部测试。",
        avoid_conditions=["干皮无保湿打底", "大量重复叠粉导致卡粉"],
        card_reason="百元以内的控油定妆选项，适合油皮混油皮随身补妆和柔焦毛孔。",
    ),
    "p_beauty_014": make_annotation(
        target_users=["油皮", "混油皮", "长时间带妆人群", "追求清透妆效的人"],
        use_cases=["空气感定妆", "通勤持妆", "约会旅行", "T区控油"],
        selling_points=["蚕丝粉体", "珍珠粉提亮", "无酒精无刺激", "经典款/控油款"],
        cautions=["粉末避免入眼", "开封后12个月内用完", "干皮建议局部使用"],
        avoid_for=["极干皮全脸大量定妆", "对粉体或珍珠粉敏感的人"],
        suitable_for=["混油皮", "油皮", "干皮夏季T区局部"],
        tags=["散粉", "蜜粉", "定妆", "控油", "提亮"],
        skin_types=["油皮", "混油皮", "多数肤质"],
        skin_concerns=["出油", "脱妆", "暗沉"],
        product_effects=["定妆", "控油", "提亮", "持妆"],
        key_ingredients=["蚕丝粉体", "珍珠粉"],
        texture="空气感散粉",
        makeup_compatibility="底妆后粉扑按压定妆，T区可加强。",
        sensitive_skin_note="宣称无酒精无刺激，但敏感肌仍需先做耳后测试。",
        avoid_conditions=["粉末入眼", "干皮保湿不足时全脸厚扑"],
        card_reason="适合想要清透定妆和控油提亮的人，油皮混油皮更匹配。",
    ),
    "p_beauty_015": make_annotation(
        target_users=["通勤上班族", "学生党", "约会聚会妆容需求", "喜欢丝绒哑光唇妆的人"],
        use_cases=["日常通勤唇妆", "约会聚会", "持久显色", "便携补妆"],
        selling_points=["仿生膜技术", "丝绒哑光", "显色持妆", "滋润不紧绷"],
        cautions=["干燥季节先用润唇膏打底", "开封后6个月内用完", "过敏应停用"],
        avoid_for=["唇部极干裂未打底的人", "不喜欢哑光妆效的人"],
        suitable_for=["日常唇妆", "需要持妆的人", "学生党", "通勤人群"],
        tags=["唇釉", "唇妆", "持妆", "显色", "滋润"],
        skin_types=["多数肤质"],
        skin_concerns=["唇部干燥", "唇妆掉色", "沾杯"],
        product_effects=["显色", "持妆", "滋润", "唇妆"],
        key_ingredients=["仿生膜技术", "透明质酸", "植物精华"],
        texture="丝绒哑光唇釉",
        makeup_compatibility="唇部彩妆，可在润唇膏打底后使用。",
        sensitive_skin_note="唇部敏感或过敏应立即停用。",
        avoid_conditions=["唇部破损", "过敏后继续使用"],
        card_reason="适合想要便携、显色和较持久唇妆的人，干唇建议先润唇打底。",
    ),
    "p_beauty_016": make_annotation(
        target_users=["25+初老眼周", "眼周干燥人群", "有细纹暗沉的人", "想全脸局部护理的人"],
        use_cases=["眼周护理", "法令纹护理", "早晚护肤", "全脸局部淡纹"],
        selling_points=["全脸可用", "玻尿酸锁水", "视黄醇衍生物", "烟酰胺提亮"],
        cautions=["避免入眼", "敏感肌先测试", "开封后6个月内用完"],
        avoid_for=["视黄醇类不耐受人群", "眼周急性敏感或破损"],
        suitable_for=["眼周干燥", "细纹", "暗沉", "初老"],
        tags=["眼霜", "淡纹", "保湿", "提亮", "抗初老"],
        skin_types=["多数肤质"],
        skin_concerns=["眼周干燥", "细纹", "暗沉", "法令纹"],
        product_effects=["保湿", "淡纹", "提亮", "抗初老"],
        key_ingredients=["玻尿酸", "视黄醇衍生物", "烟酰胺"],
        texture="轻盈眼霜",
        makeup_compatibility="眼周护肤产品，妆前需少量等待吸收。",
        sensitive_skin_note="含视黄醇衍生物和烟酰胺，敏感肌需先测试。",
        avoid_conditions=["入眼", "眼周破损", "活性成分不耐受"],
        card_reason="适合眼周干燥细纹和初抗老需求，预算不高时可作为入门眼霜。",
    ),
    "p_beauty_017": make_annotation(
        target_users=["敏感肌", "混合肌", "需要温和卸妆的人", "防水彩妆使用者"],
        use_cases=["晚间卸妆", "防水彩妆卸除", "出差便携", "毛孔清洁"],
        selling_points=["纳米级卸妆分子", "无香料", "无酒精", "无防腐剂"],
        cautions=["开封后60天内用完", "需干手干脸使用并充分乳化", "过敏期暂停使用"],
        avoid_for=["皮肤有伤口的人", "不能接受短保质期的人"],
        suitable_for=["敏感肌", "混合肌", "追求温和清洁的人", "浓妆人群"],
        tags=["卸妆", "清洁", "敏感肌", "温和", "无酒精"],
        skin_types=["敏感肌", "混合肌", "多数肤质"],
        skin_concerns=["彩妆残留", "毛孔污垢", "清洁负担"],
        product_effects=["卸妆", "清洁", "温和"],
        key_ingredients=["纳米级卸妆分子"],
        texture="卸妆油",
        makeup_compatibility="用于彩妆和防水彩妆卸除，后续温水冲洗。",
        sensitive_skin_note="通过敏感肌测试，但过敏期或有伤口时暂停使用。",
        avoid_conditions=["皮肤伤口", "开封超过60天", "乳化不充分"],
        card_reason="适合敏感肌友好的温和卸妆和防水彩妆清洁，但要注意开封后60天内用完。",
    ),
    "p_beauty_018": make_annotation(
        target_users=["油皮", "毛孔粗大人群", "预算有限的人"],
        use_cases=["控油", "平衡油脂", "提亮肤色", "入门功效精华"],
        selling_points=["烟酰胺10%", "锌1%", "平衡油脂", "百元以内"],
        cautions=["高浓度烟酰胺可能刺激", "敏感肌需建立耐受", "使用期间做好防晒"],
        avoid_for=["烟酰胺不耐受人群", "急性敏感肌"],
        suitable_for=["油皮", "预算有限", "想尝试控油提亮的人"],
        tags=["精华", "油皮", "提亮", "控油", "百元以内"],
        skin_types=["油皮", "混油皮"],
        skin_concerns=["出油", "毛孔", "暗沉"],
        product_effects=["控油", "提亮", "平衡油脂"],
        key_ingredients=["烟酰胺", "锌"],
        texture="精华液",
        makeup_compatibility="护肤精华，妆前需等待吸收。",
        sensitive_skin_note="敏感肌和烟酰胺不耐受者需谨慎。",
        avoid_conditions=["屏障受损期", "烟酰胺刺痛", "与高浓度酸类同时使用"],
        card_reason="价格低，适合预算有限且想控油提亮的人，但敏感肌要注意耐受。",
    ),
    "p_beauty_019": make_annotation(
        target_users=["干皮", "偏干肌", "换季敏感干皮", "秋冬保湿需求"],
        use_cases=["护肤第一步", "妆前保湿打底", "秋冬保湿", "出差旅行保湿"],
        selling_points=["玫瑰精华", "玻尿酸", "浓稠柔肤水", "400ml大容量"],
        cautions=["避免直接接触眼周", "敏感肌先测试", "开封后6个月内用完"],
        avoid_for=["油皮不喜欢浓稠水感的人", "预算有限且只需基础爽肤水的人"],
        suitable_for=["干皮", "偏干肌", "换季干燥", "妆前卡粉"],
        tags=["化妆水", "保湿", "干皮", "舒缓", "妆前"],
        skin_types=["干皮", "偏干肌", "敏感肌"],
        skin_concerns=["干燥", "紧绷", "换季不适", "底妆不服帖"],
        product_effects=["保湿", "舒缓", "柔润"],
        key_ingredients=["玫瑰精华", "玻尿酸"],
        texture="浓稠柔肤水",
        makeup_compatibility="妆前轻拍可提升底妆服帖度，油皮需控制用量。",
        sensitive_skin_note="换季敏感干皮可尝试，但需先局部测试。",
        avoid_conditions=["眼周直接接触", "油皮厚涂后黏腻"],
        card_reason="适合干皮秋冬保湿和妆前柔润打底，不适合追求极清爽肤感的油皮。",
    ),
    "p_beauty_020": make_annotation(
        target_users=["油皮", "混油皮", "需要长时间持妆的人"],
        use_cases=["通勤底妆", "夏日控油", "持妆遮瑕", "户外活动底妆"],
        selling_points=["持久遮瑕", "控油抗汗", "清透底妆", "SPF10 PA"],
        cautions=["干皮可能拔干", "色号需试色", "敏感肌先测试"],
        avoid_for=["干皮", "混干皮", "不喜欢哑光妆效的人"],
        suitable_for=["油皮", "混油皮", "夏季底妆"],
        tags=["底妆", "控油", "油皮", "持妆", "粉底液"],
        skin_types=["油皮", "混油皮"],
        skin_concerns=["出油", "脱妆", "遮瑕"],
        product_effects=["控油", "持妆", "遮瑕"],
        key_ingredients=["控油科技"],
        texture="清透粉底液",
        spf="SPF10",
        pa="PA",
        makeup_compatibility="底妆产品，可搭配清爽保湿妆前。",
        sensitive_skin_note="敏感肌先做测试。",
        avoid_conditions=["干皮直接上妆", "未做好保湿打底"],
        card_reason="适合油皮/混油皮长时间持妆和控油需求，干皮可能拔干。",
    ),
    "p_beauty_021": make_annotation(
        target_users=["20+眼周干纹人群", "眼周干燥紧绷人群", "妆前眼周打底需求"],
        use_cases=["眼周保湿", "熬夜后眼周急救", "妆前厚敷", "出差便携护理"],
        selling_points=["牛油果油", "维生素E", "神经酰胺", "滋润补水"],
        cautions=["不要直接厚涂猛搓", "避开眼内黏膜", "眼周敏感先测试"],
        avoid_for=["眼周易长脂肪粒且讨厌滋润感的人", "追求强抗老淡纹的人"],
        suitable_for=["眼周干燥", "卡干纹", "换季紧绷", "妆前打底"],
        tags=["眼霜", "保湿", "干纹", "妆前", "滋润"],
        skin_types=["干皮", "多数肤质"],
        skin_concerns=["眼周干燥", "干纹", "卡粉", "紧绷"],
        product_effects=["保湿", "滋润", "淡化干纹"],
        key_ingredients=["牛油果油", "维生素E", "神经酰胺"],
        texture="牛油果泥状眼霜",
        makeup_compatibility="妆前可薄涂或短时厚敷，需按摩吸收后再上遮瑕。",
        sensitive_skin_note="眼周敏感者先少量局部测试，避免入眼。",
        avoid_conditions=["眼内黏膜接触", "厚涂猛搓"],
        card_reason="更偏眼周滋润保湿和妆前不卡粉，适合眼尾干纹和干燥紧绷。",
    ),
    "p_beauty_022": make_annotation(
        target_users=["干敏肌", "换季泛红人群", "空调房干燥人群"],
        use_cases=["夜间厚敷", "密集补水", "舒缓泛红", "出差单片补水"],
        selling_points=["青刺果油", "马齿苋提取物", "密集补水", "舒缓修护"],
        cautions=["涂抹式15-20分钟后洗净", "敏感肌先测试", "避免与酸类同时使用"],
        avoid_for=["讨厌涂抹式面膜的人", "油皮怕黏腻的人"],
        suitable_for=["干皮", "敏感肌", "泛红", "缺水"],
        tags=["面膜", "保湿", "敏感肌", "舒缓", "修护"],
        skin_types=["干皮", "敏感肌"],
        skin_concerns=["干燥", "泛红", "屏障脆弱", "缺水"],
        product_effects=["保湿", "舒缓", "修护屏障"],
        key_ingredients=["青刺果油", "马齿苋提取物"],
        texture="涂抹式保湿面膜",
        makeup_compatibility="护理面膜，使用后再进行基础护肤；妆前需清洗干净并保湿。",
        sensitive_skin_note="敏感肌可尝试但首次使用仍需先测试。",
        avoid_conditions=["与酸类产品同时使用", "眼唇周围厚敷"],
        card_reason="适合干敏肌补水和舒缓泛红，夜间厚敷或换季急救更匹配。",
    ),
    "p_beauty_023": make_annotation(
        target_users=["易敏肌", "油皮", "混合皮", "日常通勤防晒人群"],
        use_cases=["通勤防晒", "短途旅行", "夏季控油防晒", "妆前防晒"],
        selling_points=["SPF50+ PA++++", "理肤泉温泉水", "清盈控油", "易敏肌适用"],
        cautions=["户外每2小时补涂", "出现红肿瘙痒应停用", "部分人可能觉得泛白"],
        avoid_for=["对防晒剂不耐受的人", "期待完全不泛白的人"],
        suitable_for=["油皮", "混合皮", "易敏肌", "通勤防晒"],
        tags=["防晒", "敏感肌", "油皮", "通勤", "控油"],
        skin_types=["油皮", "混油皮", "敏感肌"],
        skin_concerns=["防晒", "出油", "闷痘", "泛红"],
        product_effects=["防晒", "控油", "舒缓"],
        key_ingredients=["理肤泉温泉水"],
        texture="清盈防晒乳",
        spf="SPF50+",
        pa="PA++++",
        makeup_compatibility="后续上妆一般不易搓泥，需等待成膜。",
        sensitive_skin_note="易敏肌适用定位，但评论中有过敏反馈，需先测试。",
        avoid_conditions=["红肿瘙痒后继续使用", "不卸妆清洁"],
        card_reason="适合油皮混合皮的日常通勤防晒，兼顾清爽控油和易敏肌舒缓诉求。",
    ),
    "p_beauty_024": make_annotation(
        target_users=["25+初老肌", "有干纹细纹的人", "熬夜脸垮人群", "化妆卡纹人群"],
        use_cases=["抗皱淡纹", "熬夜救急", "通勤护肤", "下颌线提拉按摩"],
        selling_points=["六胜肽-1", "双重胶原肽", "肌肽抗糖", "淡纹紧致"],
        cautions=["敏感肌先测试", "避开眼周直接涂抹", "孕期建议咨询医生"],
        avoid_for=["超级敏感肌", "对胜肽类成分不耐受的人", "期待立即去除静态纹的人"],
        suitable_for=["干纹细纹", "初老", "卡粉", "熬夜松垮"],
        tags=["精华", "抗初老", "淡纹", "紧致", "300元"],
        skin_types=["多数肤质", "混油皮"],
        skin_concerns=["干纹", "细纹", "松弛", "卡粉"],
        product_effects=["抗初老", "淡纹", "紧致", "保湿"],
        key_ingredients=["六胜肽-1", "胶原肽", "肌肽"],
        texture="水感蛋清精华",
        makeup_compatibility="护肤精华，后续可叠加乳液面霜；涂太多可能搓泥。",
        sensitive_skin_note="敏感肌第一次用先耳后测试，超级敏感肌谨慎。",
        avoid_conditions=["眼周直接涂抹", "过量叠加厚重面霜"],
        card_reason="适合300元左右的初抗老淡纹需求，尤其是熬夜卡纹和轻度松垮场景。",
    ),
    "p_beauty_025": make_annotation(
        target_users=["画眉新手", "追求野生眉妆感的人", "通勤妆用户", "约会拍照妆容需求"],
        use_cases=["日常快速描眉", "通勤持妆", "约会妆造", "补眉空缺"],
        selling_points=["0.08g极细笔芯", "双头眉刷", "自然显色", "防晕染"],
        cautions=["每次只旋出1-2毫米", "避免大力按压", "油皮出油多时可能晕妆"],
        avoid_for=["额头极易出油且不定妆的人", "眉毛很浓密想快速填满的人"],
        suitable_for=["眉毛空缺", "新手画眉", "自然野生眉", "通勤妆"],
        tags=["眉笔", "眉妆", "防晕染", "新手", "持妆"],
        skin_types=["多数肤质", "油皮"],
        skin_concerns=["眉尾脱妆", "眉毛空缺", "新手手残"],
        product_effects=["眉妆", "显色", "持妆", "防晕染"],
        key_ingredients=["持色覆膜成分"],
        texture="极细双头眉笔",
        makeup_compatibility="眉部彩妆，画完可用眉刷扫开边缘，油皮可叠加眉粉定妆。",
        sensitive_skin_note="眉部皮肤敏感或破损时先暂停使用。",
        avoid_conditions=["大力按压笔芯", "高温暴晒存放", "眉部大量出油不定妆"],
        card_reason="适合新手画自然毛流感眉妆；油皮如果额头出油多，最好搭配定妆。",
    ),
}


def main() -> None:
    raw_by_id = load_raw_by_id()
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    with OUTPUT.open("w", encoding="utf-8") as f:
        for product_id in sorted(ANNOTATIONS):
            if product_id not in raw_by_id:
                raise SystemExit(f"Raw product not found: {product_id}")
            row = {"raw_product_id": product_id, **ANNOTATIONS[product_id]}
            f.write(json.dumps(row, ensure_ascii=False, sort_keys=True) + "\n")
    print(f"Wrote {len(ANNOTATIONS)} rows to {OUTPUT}")


def load_raw_by_id() -> dict[str, dict[str, Any]]:
    products: dict[str, dict[str, Any]] = {}
    for path in sorted(RAW_ROOT.glob("*/data/*.json")):
        item = json.loads(path.read_text(encoding="utf-8"))
        products[item["product_id"]] = item
    return products


if __name__ == "__main__":
    main()
